[[configuration]]
== Configuration

This section describes how to configure the deegree OAF webapp.

IMPORTANT: deegree OAF is under development, and new configuration options may be added in future releases. For the lastest parameters please consult the example workspace provided with the release version!

[[config_workspace]]
=== The OAF workspace

The deegree workspace is the modular, resource-oriented and extensible configuration concept used by deegree. The deegree OAF workspace name must be *_ogcapi-workspace_*.

The directory structure and related files are described by the following example. This example consists out of two datasets called _trees_ and _streets_ which data
is stored within a PostgreSQL/PostGIS database. The following directory structure shows the files used in this example:

.ogcapi-workspace/
----
├── config.apikey                 # <1>
└── ogcapi-workspace              # <2>
    ├── datasources
    │   └── feature               # <3>
    │       ├── streets.xml       # <4>
    │       └── trees.xml         # <5>
    ├── html                      # <6>
    │   ├── htmlview.xml          # <7>
    │   ├── streetsview.xml       # <8>
    │   ├── treesview.xml         # <9>
    │   └── default-style.css     # <10>
    ├── jdbc
    │   └── postgres-db.xml       # <11>
    ├── ogcapi                    # <12>
    │   ├── datasets.xml          # <13>
    │   ├── streets.xml           # <14>
    │   └── trees.xml             # <15>
    └── services
        ├── streets_metadata.xml  # <16>
        └── trees_metadata.xml    # <17>
----
<1> config file with APIKEY required to access REST-API (optional)
<2> the workspace root directory, the exact name is required, path can be set with environment variable `DEEGREE_WORKSPACEROOT` (mandatory)
<3> subdirectory must contain at least one feature store configuration
<4> a feature store with id _streets_
<5> a feature store with id _trees_
<6> subdirectory with the configuration of the HTML encoding (optional)
<7> global HTML encoding configuration (optional)
<8> HTML encoding configuration for the dataset streets (optional)
<9> HTML encoding configuration for the dataset trees (optional)
<10> optional CSS file (optional)
<11> configuration file required for database feature stores defining a JDBC connection (optional)
<12> subdirectory must contain at least one dataset configuration (mandatory)
<13> global dataset configuration (optional)
<14> dataset configuration for the dataset streets (mandatory)
<15> dataset configuration for the dataset trees (mandatory)
<16> metadata configuration for dataset streets (optional)
<17> metadata configuration for dataset trees (optional)

IMPORTANT: The name of the deegree workspace must be *_ogcapi-workspace_*. Using any other directory name different to this will not work with the deegree OAF webapp. This deegree workspace may contain service configuration files for deegree webservices such as WFS and WMS but those services won't be available with deegree OAF webapp!

More information about deegree's workspace concept is available in the https://download.deegree.org/documentation/current/html/#_the_deegree_workspace[deegree webservices handbook].
There you will find more information about the feature store configuration and the https://download.deegree.org/documentation/current/html/#anchor-configuration-jdbc[JDBC connection configuration].

=== Configuration files

The deegree OAF workspace adds the following directories to a standard deegree workspace:

- *dataset configuration* files in subdirectory _ogcapi/_
- *HTML encoding configuration* files in subdirectory _html/_

An deegree OAF workspace uses the following directories of a standard deegree workspace:

- *feature store configuration* files in subdirectory _datasources/feature/_
- *JDBC connection configuration* files in subdirectory _jdbc/_
- *metadata configuration* in subdirectory _services/_
- *security configuration* file named _config.apikey_ in the root directory of the workspace

The following chapters describe how to setup a deegree OAF workspace by the given example.

[[config_dataset]]
==== Dataset configuration

To provide general information about the dataset provider the following configuration file can be used:

.ogcapi/datasets.xml
[source,xml]
----
<Datasets configVersion="3.4.0"
                        xmlns="http://www.deegree.org/ogcapi/datasets"
                        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xsi:schemaLocation="http://www.deegree.org/ogcapi/datasets  http://schemas.deegree.org/ogcapi/datasets/3.4.0/datasets.xsd">
  <Title>Datasets Title</Title>
  <Description>Datasets Description</Description>
  <Contact>
    <Name>Contact Name</Name>
    <Url>https://www.deegree.org</Url>
    <EMail>info@deegree.org</EMail>
  </Contact>
</Datasets>
----

NOTE: The file _datasets.xml_ shall be stored in the subdirectory _ogcapi/_. The file is optional.

This configuration file can contain the following elements:

[width="100%",cols="25%,15%,20%,40%",options="header",]
|===
|Option |Cardinality |Value |Description
|Title |0..1 |String |Title
|Description |0..1 |String |Description
|Contact |0..1 |Complex |Contact configuration
|===

The element ```<Contact/>``` has the following subelements:

[width="100%",cols="25%,15%,20%,40%",options="header",]
|===
|Option |Cardinality |Value |Description
|Name |0..1 |String |Name of the dataset provider
|Url |0..1 |String |URL of the dataset provider
|Email |0..1 |String |Email of the dataset provider
|===

NOTE: The content of this file is returned under the resource _/datasets_.

Each dataset is configured in a separate file. The following example shows a minimal configuration for a dataset called "streets". The filename defines the _{datasetId}_.

.ogcapi/streets.xml
[source,xml]
----
<deegreeOAF configVersion="3.4.0"
            xmlns="http://www.deegree.org/ogcapi/features"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.deegree.org/ogcapi/features http://schemas.deegree.org/ogcapi/features/3.4.0/features.xsd">

  <FeatureStoreId>streets</FeatureStoreId>  <!--1-->

  <QueryCRS>http://www.opengis.net/def/crs/OGC/1.3/CRS84</QueryCRS>  <!--2-->
  <QueryCRS>EPSG:4326</QueryCRS>  <!--3-->

  <HtmlViewId>streetview</HtmlViewId>  <!--4-->

</deegreeOAF>
----
<1> Identifier of the feature store configuration, links to file _datasources/feature/streets.xml_.
<2> Mandatory CRS, first CRS must be `http://www.opengis.net/def/crs/OGC/1.3/CRS84` to be conform to OGC API Features Core.
<3> Additional CRS, to retrieve data in the given CRS the optional query parameter `+{crs}+` needs to be used, see section <<query_parameter>> for more information.
<4> Identifier of the HTML encoding configuration, links to file _html/streetsview.xml_.

The next example shows a configuration for a dataset called "trees" with all options available.

.ogcapi/trees.xml
[source,xml]
----
<deegreeOAF configVersion="3.4.0"
            xmlns="http://www.deegree.org/ogcapi/features"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.deegree.org/ogcapi/features http://schemas.deegree.org/ogcapi/features/3.4.0/features.xsd">

  <FeatureStoreId>trees</FeatureStoreId>  <!--1-->

  <QueryCRS>http://www.opengis.net/def/crs/OGC/1.3/CRS84</QueryCRS>  <!--2-->
  <QueryCRS>EPSG:4326</QueryCRS>  <!--3-->

  <DateTimeProperties>
    <DateTimeProperty> <!--4-->
      <FeatureTypeName xmlns:app="http://www.deegree.org/app">app:trees</FeatureTypeName>
      <PropertyName xmlns:app="http://www.deegree.org/app">app:seedyear</PropertyName>
    </DateTimeProperty>
  </DateTimeProperties>

  <HtmlViewId>treesview</HtmlViewId>  <!--5-->

  <Metadata>
    <ProviderLicense> <!--6-->
      <Name>ProviderLicense</Name>
      <Url>https://www.apache.org/licenses/LICENSE-2.0</Url>
    </ProviderLicense>
    <DatasetLicense>  <!--7-->
      <Name>DatasetLicense</Name>
      <Url>https://www.apache.org/licenses/LICENSE-2.0</Url>
    </DatasetLicense>
    <DatasetCreator> <!--8-->
      <Name>Dataset Creator Name</Name>
      <Url>http://deegree-enterprise.de</Url>
      <EMail>info@deegree-enterprise.de</EMail>
    </DatasetCreator>
    <MetadataURL format="application/xml">http://example.metadata.org?service=CSW&amp;request=GetRecordById&amp;version=2.0.2&amp;id=1234</MetadataURL> <!--9-->
    <MetadataURL format="text/html">http://example.metadata.org/path_to_html/1234</MetadataURL> <!--10-->
  </Metadata>

</deegreeOAF>
----
<1> Identifier of the feature store configuration, links to file _datasources/feature/trees.xml_.
<2> Mandatory CRS, first CRS must be http://www.opengis.net/def/crs/OGC/1.3/CRS84 to be conform to OGC API Features Core.
<3> Additional CRS, to retrieve data in the given CRS the optional query parameter `+{crs}+` needs to be used, see section <<query_parameter>> for more information.
<4> DateTime property defines a property _app:seedyear_ of the feature type _app:trees_ as a datetime property.
<5> Identifier of the HTML encoding configuration, links to file _html/treesview.xml_.
<6> Provider license applicable to the service provider
<7> Dataset license applicable to the dataset
<8> Dataset provider contact details
<9> Metadata link in format `application/xml` for the dataset
<10> Metadata link in format `text/html` for the dataset

NOTE: The dataset configuration file must be stored in the subdirectory _ogcapi/_. The file is mandatory.

This configuration file can contain the following elements:

[width="100%",cols="25%,15%,20%,40%",options="header",]
|===
|Option |Cardinality |Value |Description
|FeatureStoreId |0..n |String |Identifier of a feature store, see <<config_feature_store>> which implementations are supported. This identifier also defines the _{collectionId}_
|QueryCRS |0..n |String |The CRS codes supported, `CRS84` must be provided as the first element
|DateTimeProperties |0..1 |Complex |Configuration of date and time properties, see http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_parameter_datetime[parameter datetime in the OGC API specification] for more information
|HtmlViewId |0..1 |String |Identifier of the HTML encoding configuration, see <<config_htmlview>> for more information
|Metadata |0..1 |Complex |Configuration of the dataset metadata
|===

The element ```<DateTimeProperties/>``` can contain multiple elements of ```<DateTimeProperty/>``` which has the following subelements:

[width="100%",cols="25%,15%,20%,40%",options="header",]
|===
|Option |Cardinality |Value |Description
|FeatureTypeName |0..1 |String |QName of the feature type
|PropertyName |0..1 |String |QName of the property
|===

The element ```<Metadata/>``` has the following subelements:

[width="100%",cols="25%,15%,20%,40%",options="header",]
|===
|Option |Cardinality |Value |Description
|ProviderLicense |0..1 |Complex |License of the dataset provider
|DatasetLicense |0..1 |Complex |License of the dataset
|DatasetCreator |0..1 |Complex |Contact details of the dataset creator
|MetadataURL |0..n |URL |URL of the metadata record describing the dataset, use the attribute `format` to link HTML or XML representation.
|===

[[config_feature_store]]
==== Feature store configuration

Currently, deegree OAF supports the following feature stores:

- `SQLFeatureStore` - retrieves data from a database supporting an extended mapping.
- `SimpleSQLFeatureStore` - retrieves data from a database using a single table mapping.
- `MemoryFeatureStore` - retrieves data from a file in GML file format.
- `ShapeFeatureStore` - retrieves data from a file in SHAPE file format. The Storage CRS is required when using the ShapeFeatureStore.

The supported databases for `SQLFeatureStore` and `SimpleSQLFeatureStore` are:

- Oracle database, and
- PostgreSQL/PostGIS database.

A detailed documentation of the feature store configuration is described in section "Feature Stores"
of the https://download.deegree.org/documentation/current/html/#anchor-configuration-featurestore[deegree webservices handbook].

NOTE: The _{featureId}_ is defined by the feature store configuration. Use the element `<FIDMapping/>` to define the mapping of this attribute.

[[config_htmlview]]
==== HTML encoding configuration

To configure the HTML encoding a configuration file can be used. The following example contains the configuration for the dataset _trees_.

.html/treesview.xml
[source,xml]
----
<HtmlView configVersion="3.4.0"
          xmlns="http://www.deegree.org/ogcapi/htmlview"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.deegree.org/ogcapi/htmlview http://schemas.deegree.org/ogcapi/3.4.0/htmlview.xsd">

  <CssFile>../html/lgv.css</CssFile>  <!--1-->
  <LegalNoticeUrl>https://www.hamburg.de/legalNotice/</LegalNoticeUrl> <!--2-->
  <PrivacyPolicyUrl>https://www.hamburg.de/datenschutz/</PrivacyPolicyUrl> <!--3-->
  <DocumentationUrl>https://www.hamburg.de/</DocumentationUrl> <!--4-->
  <Map>
    <WMSUrl>https://geodienste.hamburg.de/HH_WMS_Cache_Stadtplan</WMSUrl> <!--5-->
    <WMSLayers>stadtplan</WMSLayers> <!--6-->
    <CrsProj4Definition code="EPSG:25832">+proj=utm +zone=32 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs</CrsProj4Definition> <!--7-->
  </Map>

</HtmlView>
----
<1> optional CSS file used for all HTML views (optional)
<2> link to page containing the publishing, copyright, and legal information
<3> link to page containing the privacy policy
<4> link to page containing the documentation
<5> URL of WMS used for the base map
<6> layer name of the base map
<7> CRS configuration of the base map

NOTE: The file _treesview.xml_ must be stored in the subdirectory _html/_. To define a global configuration the file name must be _htmlview.xml_. The file is optional.

This configuration file can contain the following elements:

[width="100%",cols="25%,15%,20%,40%",options="header",]
|===
|Option |Cardinality |Value |Description
|CssFile |0..1 |URI |relative path to a CSS file
|LegalNoticeUrl |0..1 |URL |URL to external page containing the legal notice used for link in footer "Legal Notice"
|PrivacyPolicyUrl |0..1 |URL |URL to an external page containing the privacy policy for link in footer "Privacy Policy"
|DocumentationUrl |0..1 |URL |URL to an external page containing the documentation, if not set link in footer "Help" refers to this documentation
|Map |0..1 |Complex |Configuration for the base map
|===

The element ```<Map/>``` has the following subelements:

[width="100%",cols="25%,15%,20%,40%",options="header",]
|===
|Option |Cardinality |Value |Description
|WMSUrl |1 |URL |WMS service endpoint URL
|WMSLayers |1 |String |Name of the layer
|CrsProj4Definition |1 |String |Use the attribute `code` to set the EPSG code, and the value element for the https://proj.org[PROJ] definition as provided by http://epsg.io.
|===

Additional information about the option `CssFile`: The following elements can be configured using a CSS file: the background color of header and footer, images in header and footer, links to help, legal notice, and privacy policy.

[[config_metadata]]
==== Metadata configuration

The service metadata can be defined for each dataset. Use a file name ending with _{datasetId}_metadata.xml_ to define the service metadata per dataset.
Use the dataset identifier as a prefix. For example if you have a dataset configured in _streets.xml_ the related metadata file has the file name _streets_metadata.xml_.

The following excerpt of the _streets_metadata.xml_ shows which options are available:

.services/streets_metadata.xml
[source,xml]
----
<deegreeServicesMetadata>

  <ServiceIdentification> <!--1-->
    <Title>deegree OGC API - Features</Title>
    <Abstract>Streets of the city of Hamburg</Abstract>
  </ServiceIdentification>

  <DatasetMetadata>
    <MetadataUrlTemplate>http://example.metadata.org/services/csw?service=CSW&amp;request=GetRecordById&amp;version=2.0.2&amp;id=${metadataSetId}</MetadataUrlTemplate> <!--2-->
    <MetadataUrlTemplate format="text/html">http://example.metadata.org/csw/htmlrepaesentation/${metadataSetId}</MetadataUrlTemplate> <!--3-->
    <Dataset>
      <Name xmlns:app="http://www.deegree.org/app">app:streets</Name> <!--4-->
      <Title>Streets</Title> <!--5-->
      <Abstract>Streets of the city of Hamburg</Abstract>
      <MetadataSetId>beefcafe-beef-cafe-beef-cafebeefcaf</MetadataSetId>
    </Dataset>
  </DatasetMetadata>

</deegreeServicesMetadata>
----
<1> Information about the service, in the context of OAF it is used per dataset
<2> Service metadata link
<3> Service metadata link in format `text/html`
<4> Dataset name which links to the feature type configured, here the {collectionId}
<5> Title of the feature collection, used in HTML encoding instead of the {collectionId}

NOTE: The file _streets_metadata.xml_ must be stored in the subdirectory _services/_. The file is mandatory.

A detailed documentation of the metadata configuration is described in section "Metadata"
of the https://download.deegree.org/documentation/current/html/#anchor-configuration-service-metadata[deegree webservices handbook].

[[config_restapi]]
=== deegree config REST-API

deegree OAF provides a REST-API for configuration purposes. As in https://download.deegree.org/documentation/current/html/#anchor-configuration-restapi[deegree webservices] a client can use the REST interface to manage the configuration. The following operations are supported:

```
[HTTP METHOD] [RESOURCE] - [DESCRIPTION]
GET /config/download[/path] - download currently running workspace or file in workspace
GET /config/restart - restart currently running workspace
GET /config/restart[/path] - restarts all resources connected to the specified one
GET /config/restart/wsname - restart with workspace <wsname>
GET /config/update - update currently running workspace, rescan config files and update resources
GET /config/update/wsname - update with workspace <wsname>, rescan config files and update resources
GET /config/list[/path] - list currently running workspace or directory in workspace
GET /config/list/wsname[/path] - list workspace with name <wsname> or directory in workspace
GET /config/validate[/path] - validate currently running workspace or file in workspace
GET /config/validate/wsname[/path] - validate workspace with name <wsname> or file in workspace
GET /config/update/bboxcache[?featureStoreId=] - recalculates the bounding boxes of all feature stores of the currently running workspace, with the parameter 'featureStoreId' a comma separated list of feature stores to update can be passed
GET /config/update/bboxcache/wsname[?featureStoreId=] - recalculates the bounding boxes of all feature stores of the workspace with name <wsname>, with the parameter 'featureStoreId' a comma separated list of feature stores to update can be passed
PUT /config/upload/path/file - upload file into current workspace
PUT /config/upload/wsname/path/file - upload file into workspace with name <wsname>
DELETE /config/delete[/path] - delete currently running workspace or file in workspace
DELETE /config/delete/wsname[/path] - delete workspace with name <wsname> or file in workspace
```

The REST-API is enabled by default. To protect this interface from unauthorized use, it is automatically secured with a so-called API key. Each HTTP request requires that the API key contained in the file _config.apikey_ is transferred.

A detailed documentation of the REST-API interface and how access is configured is described in section "15.1. Usage of the interface"
of the deegree webservices handbook.footnote:[Documentation provided with deegree Enterprise, file: _documentation/manuals/deegree-core-documentation.pdf_].
