== Help

This section show how to get help in case of problems.

[[help_knownIssues]]
=== Known Issues

* Mixing legacy service configuration with OGC API configuration is currently not supported by deegree OAF webapp. See the <<help_faq>> how to serve your data with deegree webservices and deegree OAF from the same workspace configuration.

* Startup time of deegree OAF webapp may increase noticeably when the deegree workspace contains many resources (e.g. more than 100 files).

* Using the browser's navigation buttons when using the HTML view may result in empty pages or the switch to JSON encoding. Affected browsers: Google Chrome, Chromium. You can avoid this by enabling the Vary HTTP response header in your HTTP server configuration. Check the HTTP server documentation how to configure this.

* The implementation supports only parts of OGC API - Features - Part 3. The implementation is not fully supporting the following requirements classes: "Queryables", "Queryables as Query Parameters", "Filter" with "CQL2 Functions", and "Features Filter".

[[help_support]]
=== Support

Use the deegree support options (mailing lists, commercial support) to get help.

[[help_faq]]
=== FAQ
[qanda]
How to update the _bbox_cache.properties_?::

  Use REST-API operation `/config/update/bboxcache` to recalculate the bounding boxes of the feature stores. See section <<config_restapi>> for more information how to use the REST-API.

How to migrate an existing deegree workspace?::

  Given that an existing deegree workspace contains at least one feature store the following steps need to be done to provide the data via deegree OAF webapp:

- Add a dataset configuration file in subdirectory _ogcapi/_, e.g. _streets.xml_ as described in the example workspace in chapter <<config_dataset>>.
- Configure the HTML encoding by adding a file in subdirectory _html/_ (optional), e.g. _streetsview.xml_ as described in the example workspace in chapter <<config_htmlview>>.
- Deploy the deegree OAF webapp as described in chapter <<installation_deploy>>.
- Add mapping entry to _webapps.properties_ file to select the deegree OAF workspace for the deegree OAF webapp.

How to use the same workspace with deegree OAF and deegree webservices?::

  Deploy both webapps for deegree OAF and deegree webservices configured to use the same workspace called _ogcapi-workspace_. Use the file _webapps.properties_ to configure this. Keep in mind that deegree OAF will provide the OGC API - Features and deegree webservices will provide only the legacy service implementations. You may see warnings in the logging messages for both instances that configuration files have been ignored.

How to deploy multiple instances of deegree OAF webapp?::

  Multiple deployments of the webapp are possible. Since each instance of the runtime environment can host one or more webapp. For every deployed webapp there must be a deegree workspace available with the name *_ogcapi-workspace_*. It is possible that multiple instances of the webapp can share one single instance of a deegree workspace, for example a setup serving the same data by multiple instances in a load-balancing scenario. To serve different data configured in different deegree workspace's you need to run multiple instances of the runtime environment.
Use the environment variable `DEEGREE_WORKSPACE_ROOT` to set the path to the deegree workspace directory. Read further in section <<configuration>> about the deegree workspace and configuration files.
