[[installation]]
== Installation

There are many ways to install deegree OAF on a server. This section will describe the various installation paths available.

[[requirements]]
=== Requirements

deegree OAF works on every Java Servlet container implementing the Java Servlet API 3.1 using an OpenJDK or Oracle JRE 8. The JRE and Java Servlet container constitute the runtime environment.
The installation of these components must be done prior of this installation.

The server hosting the service should have at least 4 GB of free memory and more than 2 CPU cores available.

NOTE: OpenJDK 8 with https://tomcat.apache.org/download-90.cgi[Apache Tomcat 9] is the recommended runtime environment.

=== Download

The deegree OAF webapp is provided as a WAR file with the name *_deegree-ogcapi-webapp-postgres.war_* for PostgreSQL and *_deegree-ogcapi-webapp-oracle.war_* for Oracle database from the deegree Enterprise repository.footnote:[URL is http://buildserver.deegree-enterprise.de/nexus/. Please contact support@deegree-enterprise.de for detailed information how to access the artifacts.].
Both artifacts contain all required libraries and feature store implementations to access file-based feature stores (see <<config_feature_store>> for more information which feature stores are supported).
Download the WAR file and store it in the local file system of the server.

[[installation_deploy]]
=== Deploy the webapp

Move the WAR file to the deployment folder of the runtime environment. For Apache Tomcat the folder is `$CATALINA_HOME/webapps`.

NOTE: Within this document the context path _deegree-services-oaf_ for the deegree OAF webapp is used. Rename the WAR file to _deegree-services-oaf.war_ to follow this convention.

Multiple deployments of the webapp are possible. Since each instance of the runtime environment can host one or more webapp. For every deployed webapp there must be a deegree workspace available with the name *_ogcapi-workspace_*. It is possible that multiple instances of the webapp can
share one single instance of a deegree workspace, for example a setup serving the same data by multiple instances in a load-balancing scenario. To serve different data configured in different deegree workspace's you need to run multiple instances of the runtime environment.
Use the environment variable `DEEGREE_WORKSPACEROOT` to set the path to the deegree workspace directory. Read further in section <<configuration>> about the deegree workspace and configuration files.

NOTE: Deploying one single webapp per runtime instance is recommended.

[[start_webapp]]
=== Start the webapp

To start the webapp the runtime environment needs to be started. For Apache Tomcat use the start script `$CATALINA/bin/startup.sh`.

[[stop_webapp]]
=== Stop the webapp

To stop the webapp the runtime environment needs to be stopped. For Apache Tomcat use the start script `$CATALINA/bin/shutdown.sh`.

=== Uninstallation

To uninstall the webapp:

1. Stop the runtime environment (if it is running).
2. Delete the webapp and the directory in which the deegree OAF webapp is installed.

=== Docker

With deegree Enterprise a Docker Image with deegree OAF is available.footnote:[Please contact support@deegree-enterprise.de for more information.]. When using the Docker image the installation of Docker is required. Check the https://docs.docker.com/get-docker/[Docker Documentation] for requirements and installation instructions.
The docker image provides all software components and no additional software installations are necessary.
