== Introduction

The deegree OGC API Feature (OAF) implementation is compliant to the latest OGC Standard called
http://docs.opengeospatial.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core]. deegree OAF provides a server implementation that  has been developed based on deegree's
existing workspace concept using the API of deegree.

=== The OGC API family

The OGC API family of standards are being developed to make it easy for anyone to provide geospatial data to the web. These standards build upon the legacy of the OGC Web Service standards (WMS, WFS, WCS, WPS, etc.), but define resource-centric APIs that take advantage of modern web development practices.

Read more at http://www.ogcapi.org[www.ogcapi.org] about the new standards and their goals.

=== Features

deegree OAF supports the following Conformance Classes:

* Core

Based on that requirements class deegree OAF provides implementations of representations for spatial data using encodings such as:

* HTML,
* GeoJSON,
* Geography Markup Language (GML), Simple Features Profile, Level 0, and
* Geography Markup Language (GML), Simple Features Profile, Level 2.

The Web API is provided as an Open API 3.0 document implementing the requirements class:

* OpenAPI Specification 3.0.

=== Quick Start

. Install the deegree OAF webapp on your preferred Java Servlet container (the runtime environment). See section <<Installation>> for more information.
. Create the necessary deegree configuration files stored within a deegree workspace with at least one datasource. Which files are required is described in section <<Configuration>>.
. Start the runtime environment containing the deegree OAF webapp.
. Start a browser and open the OpenAPI specification.
. Browse the content using the HTML encoding. How to use the HTML encoding to access the data is described in section <<html_encoding>>.

== Terms and Definitions

=== dataset
Is a collection of data. In the context of deegree OAF a dataset is the set of feature types provided by a feature store.

=== datasource
Is a source containing data such as a file or a database. In the context of deegree OAF a datasource can be a feature store implementation.

=== feature
Is an abstraction of real world phenomena. In the context of deegree OAF it is a spatial entity stored in a datasource.

=== feature collection
Is a set of features from a dataset.

=== feature store
Is a ressource within the deegree workspace providing access to a feature collection. In the context of deegree OAF it can be feature store retrieving data from a SHAPE file or a database.

=== WebAPI
An API using an architectural style that is based upon open standards and best practices such as https://swagger.io/specification/[OpenAPI Specification] and it's implementation https://swagger.io/[Swagger].

=== webapp
Is a deployable instance of a web application. In the context of deegree OAF it is a Web application ARchive (WAR) containing all resources that together constitute the deegree OAF application.

=== workspace
Is a directory structure containing configuration files. Most configuration files are in XML format.
More information about deegree's workspace concept is available in the https://download.deegree.org/documentation/current/html/[deegree webservices handbook].